# MPL
version: '3'
services:
  nginx:
    container_name: mpl-nginx
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
      - "21:21"
    links:
      - nodejs:nodejs
    volumes:
      # config, SSLs, caches, logs
      - ./config/nginx/vhost-${ENV}.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./config/nginx/nginx.key:/etc/nginx/ssl/nginx.key
      - ./log/nginx:/var/log/nginx
      - ./cache/nginx:/var/cache/nginx
  nodejs:
    container_name: mpl-nodejs
    restart: always
    build: ./nodejs
    # ports:
    #   - "3000:3000"
    volumes:
      - ./nodejs/app:/usr/src/app
    tty: true